language: go
install:
  - cd liblbfgs && ./autogen.sh && ./configure && sudo make install && cd ..
  - cd crfsuite && ./autogen.sh && ./configure && sudo make install && cd ..
  - sudo cp /usr/local/lib/liblbfgs.so /lib/liblbfgs-1.10.so
  - sudo cp /usr/local/lib/libcqdb.so /lib/libcqdb-0.12.so
  - sudo cp /usr/local/lib/libcrfsuite.so /lib/libcrfsuite-0.12.so
