language: go
install:
  - cd liblbfgs && ./autogen.sh && ./configure && sudo make install && cd ..
  - cd crfsuite && ./autogen.sh && ./configure && sudo make install && cd ..
  - cp /usr/local/lib/libcrfsuite.so /lib/libcrfsuite-0.12.so
